kill -STOP $(ps -ef | grep ksh | grep search_porn | awk '{ print $2 }' )
kill -STOP $(ps -ef | grep ksh | grep search_fantastic | awk '{ print $2 }' )
kill -STOP $(ps -ef | grep ksh | grep search_you.ksh | awk '{ print $2 }' )
kill -STOP $(ps -ef | grep ksh | grep search_wshh.ksh | awk '{ print $2 }' )
kill -STOP $(ps -ef | grep ksh | grep single_youtube.ksh | awk '{ print $2 }' )
kill -STOP $(ps -ef | grep ksh | grep search_dailymotion.ksh | awk '{ print $2 }' )
